version: '3'
services:
  mariadb:
    image: mariadb:${MARIADB_VERSION:-10.4.18}
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        VERSION: ${MARIADB_VERSION}
        REL: focal
    volumes:
      - ./tuning.cnf:/etc/mysql/conf.d/tuning.cnf
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: magentodb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypass
    healthcheck:
        test: ["CMD-SHELL", "healthcheck.sh", "--connect"]
        interval: 20s
        timeout: 5s
        retries: 5
